name: Parkour
main: Parkour\Main
version: 2.0.1
api: [1.0.0]
author: Driesboy
commands:
 parkour:
  description: clear checkpoints
  permission: parkour
  clearparkour:
  description: clear checkpoints
  permission: parkour.clear
  toparkour:
  description: go to checkpoint
  permission: parkour.goto
permissions:
 parkour.clear:
   description: clear checkpoints
   default: default
   parkour.goto:
   description: clear checkpoints
   default: default
