# _____       _           _                 
#|  __ \     (_)         | |                
#| |  | |_ __ _  ___  ___| |__   ___  _   _ 
#| |  | | '__| |/ _ \/ __| '_ \ / _ \| | | |
#| |__| | |  | |  __/\__ \ |_) | (_) | |_| |
#|_____/|_|  |_|\___||___/_.__/ \___/ \__, |
#                                      __/ |
#                                     |___/
CheckpointSaved: §7> §aCheckpoint saved§e!
TeleportMessage: §7> §aTeleported back to your set checkpoint§e!
reward-command: givemoney {PLAYER} 50
EarnReward: §7> §aYou've finished the parkour§e! §bGood job§e!
No-Checkpoint: §7> §cNo checkpoint found§e.
ClearParkour: §7> §cSuccesfull cleared checkpoints§e.
CheckPointBlock: 247
world: Rainbow Void Parkour
